function on_update()
    	spawn_predbannik_teleports()
end

function spawn_predbannik_teleports()
    	if not has_alife_info("predbannik_tp_spawned") and level.name()=="predbannik" then
        		alife():create("1beer_teleport_predbannik1", vector():set(-106, 32, 200), 818475, 686)
        		alife():create("1beer_teleport_predbannik2", vector():set(-221, 8, -308), 598185, 690)
				db.actor:give_info_portion("predbannik_tp_spawned")
    	end
end